#!/bin/sh
# Phase 09D D10 — writes infra/prod/.env (mode 600, git-ignored) from .env.example.
#   * SECRETS are generated here with strong randomness (openssl rand) - never typed by a human.
#   * EXTERNAL values (host, Razorpay, Brevo ...) are prompted for, or - with --non-interactive -
#     read from environment variables of the same name (used by CI and rebuild automation).
# Refuses to overwrite an existing .env unless --force is given (rotating secrets logs everyone out).
set -eu
# shellcheck source=lib.sh
. "$(dirname "$0")/lib.sh"

INTERACTIVE=1
FORCE=0
for arg in "$@"; do
    case "$arg" in
        --non-interactive) INTERACTIVE=0 ;;
        --force) FORCE=1 ;;
        *) die "unknown option: $arg (use --non-interactive, --force)" ;;
    esac
done

EXAMPLE="$PROD_DIR/.env.example"
[ -f "$EXAMPLE" ] || die "$EXAMPLE missing"
if [ -f "$ENV_FILE" ] && [ "$FORCE" -ne 1 ]; then
    die "$ENV_FILE already exists. Re-running would replace every secret (all users signed out). Use --force to overwrite."
fi
command -v openssl >/dev/null 2>&1 || die "openssl is required"

# 48 random bytes -> 64 base64 chars, made URL/shell/YAML safe (only letters and digits).
rand_secret() { openssl rand -base64 48 | tr -d '\n=+/' | cut -c1-48; }
rand_hex() { openssl rand -hex "$1"; }

# Prompt (or read from the environment) for an external value. $1=name $2=default $3=required(1/0)
ask() {
    name=$1; default=$2; required=$3
    eval "current=\${$name:-}"
    if [ -n "$current" ]; then ANSWER=$current; return; fi
    if [ "$INTERACTIVE" -eq 1 ]; then
        printf '%s%s: ' "$name" "${default:+ [$default]}" >&2
        read -r ANSWER || ANSWER=""
        [ -n "$ANSWER" ] || ANSWER=$default
    else
        ANSWER=$default
    fi
    if [ "$required" -eq 1 ] && [ -z "$ANSWER" ]; then
        die "$name is required"
    fi
}

TMP=$(mktemp)
trap 'rm -f "$TMP"' EXIT
umask 077

emit() { printf '%s=%s\n' "$1" "$2" >> "$TMP"; }
# Values are single-quoted so spaces / # / < > in e.g. MAIL_FROM survive both `docker compose`
# and `. .env`. A single quote inside a value is rejected (it would end the quoting).
emit_q() {
    case "$2" in *"'"*) die "$1 must not contain a single quote" ;; esac
    printf "%s='%s'\n" "$1" "$2" >> "$TMP"
}

log "Generating secrets..."
{
    echo "# Generated by infra/prod/scripts/generate-env.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ). Do not commit."
} >> "$TMP"

ask SITE_HOST "" 1;                 emit_q SITE_HOST "$ANSWER"
ask ADMIN_EMAILS "" 0;              emit_q ADMIN_EMAILS "$ANSWER"
ask SUPPORT_EMAIL "" 0;             emit_q SUPPORT_EMAIL "$ANSWER"
ask HTTP_PORT 80 0;                 emit HTTP_PORT "$ANSWER"
ask HTTPS_PORT 443 0;               emit HTTPS_PORT "$ANSWER"

emit DB_PASSWORD "$(rand_secret)"
emit JWT_SECRET "$(rand_secret)"
emit DRM_SIGNING_SECRET "$(rand_secret)"
emit MINIO_ROOT_USER "sl$(rand_hex 6)"
emit MINIO_ROOT_PASSWORD "$(rand_secret)"
emit REDIS_PASSWORD "$(rand_secret)"

ask GOOGLE_CLIENT_ID "" 0;          emit_q GOOGLE_CLIENT_ID "$ANSWER"
emit PAYMENT_GATEWAY "${PAYMENT_GATEWAY:-razorpay}"
ask RAZORPAY_KEY_ID "" 1;           emit_q RAZORPAY_KEY_ID "$ANSWER"
ask RAZORPAY_KEY_SECRET "" 1;       emit_q RAZORPAY_KEY_SECRET "$ANSWER"
ask RAZORPAY_WEBHOOK_SECRET "" 1;   emit_q RAZORPAY_WEBHOOK_SECRET "$ANSWER"

ask MAIL_HOST smtp-relay.brevo.com 0; emit_q MAIL_HOST "$ANSWER"
ask MAIL_PORT 587 0;                emit MAIL_PORT "$ANSWER"
ask MAIL_USER "" 0;                 emit_q MAIL_USER "$ANSWER"
ask MAIL_PASS "" 0;                 emit_q MAIL_PASS "$ANSWER"
ask MAIL_FROM "" 0;                 emit_q MAIL_FROM "$ANSWER"

ask SENTRY_DSN "" 0;                emit_q SENTRY_DSN "$ANSWER"
ask VITE_SENTRY_DSN "" 0;           emit_q VITE_SENTRY_DSN "$ANSWER"
ask VITE_LEGAL_REVIEWED "" 0;       emit_q VITE_LEGAL_REVIEWED "$ANSWER"

ask OCI_S3_ENDPOINT "" 0;           emit_q OCI_S3_ENDPOINT "$ANSWER"
ask OCI_S3_BUCKET secureleaf-backups 0; emit_q OCI_S3_BUCKET "$ANSWER"
ask OCI_S3_ACCESS_KEY "" 0;         emit_q OCI_S3_ACCESS_KEY "$ANSWER"
ask OCI_S3_SECRET_KEY "" 0;         emit_q OCI_S3_SECRET_KEY "$ANSWER"
emit_q BACKUP_BUCKETS "${BACKUP_BUCKETS:-secureleaf-raw secureleaf-tiles secureleaf-thumbnails}"
emit_q MINIO_IMAGE "${MINIO_IMAGE:-quay.io/minio/minio:latest}"
emit_q MC_IMAGE "${MC_IMAGE:-quay.io/minio/mc:latest}"

install -m 600 "$TMP" "$ENV_FILE"
log "Wrote $ENV_FILE (mode 600)."
